### ISSUE TITLE
Copying result to clipboard

### ISSUE THREAD

**Issue by hcgraf** [arecarn/vim-crunch#54]
According to `:help clipboard` (after the `Note`):
```
When the "unnamed" string is included in the 'clipboard' option, the unnamed
register is the same as the "* register.  Thus you can yank to and paste the
selection without prepending "* to commands.
```
So it should be always ok to yank into the unnamed register like here:
https://github.com/arecarn/vim-crunch/blob/7a4bc1cc5a0e368564e254a4026524d6a3ed2522/autoload/crunch.vim#L64

No need to check for `clipboard` :) This would have the additional benefit that it will also work if the vim version doesn't have the clipboard option.

**Comment by arecarn** [comment]
I don't think it's entirely true that I don't need to check for clipboard. I played with it a little bit and it seems behavior in the help regarding "unnamed" don't apply for setreg(). In reading the note I gues this is because when `setreg` is called it's not yanking or pasting a selection. On the other hand I would be happy to be proved otherwise. 

I do think it's possible I might be doing at least something wrong in the clipboard code though, so I'll keep this open take another look, when I get the chance.
